import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "./contexts/cart-context";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Medicine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          {children}
          <Toaster />
        </CartProvider>
      </body>
    </html>
  );
}
